#ifndef COMMONRULES_H
#define COMMONRULES_H



// Common rule defines
enum CostType
{
    COSTTYPE_INVALID = -1,
    COSTTYPE_PER_LEVEL,
    COSTTYPE_NORMAL,
    COSTTYPE_ARRAY,
    NUM_COSTTYPES
};
enum ActivationType
{
    ACTIVATIONTYPE_INVALID = -1,
    ACTIVATIONTYPE_INTERRUPT,
    ACTIVATIONTYPE_FREE,
    ACTIVATIONTYPE_SIMPLE,
    NUM_ACTIVATIONTYPES
};

#endif // COMMONRULES_H
