// Resource categories - THE ORDER IS OMPORTANT
enum ResourceType
{
    RESOURCE_TYPE_INVALID = -1,
    RESOURCE_TYPE_MELEE_WEAPON,
    RESOURCE_TYPE_PROJECTILE_WEAPON,
    RESOURCE_TYPE_FIREARM,
    RESOURCE_TYPE_AMMUNITION,
    RESOURCE_TYPE_EXPLOSIVES,
    RESOURCE_TYPE_CLOTHING_ARMOR,
    RESOURCE_TYPE_ELECTRONICS,
    RESOURCE_TYPE_INDUSTRIAL_CHEMICALS,
    RESOURCE_TYPE_SURVIVAL_GEAR,
    RESOURCE_TYPE_GRAPPLE_FLARE,
    RESOURCE_TYPE_BIOTECH,
    RESOURCE_TYPE_DOCWAGON,
    RESOURCE_TYPE_AUGMENTATION,
    RESOURCE_TYPE_MAGICAL_EQUIPMENT,
    RESOURCE_TYPE_VEHICLES_DRONES,
    NUM_RESOURCE_TYPES
};

// Resource sub-types, those are simple defines as they represent the index within
// a resource category
#define RESOURCE_SUBTYPE_MELEE_BLADES           0
#define RESOURCE_SUBTYPE_MELEE_CLUBS            1
#define RESOURCE_SUBTYPE_MELEE_OTHER            2
#define RESOURCE_SUBTYPE_PROJECTILE_BOWS        0
#define RESOURCE_SUBTYPE_PROJECTILE_CROSSBOWS   1
#define RESOURCE_SUBTYPE_PROJECTILE_THROWING    2
#define RESOURCE_SUBTYPE_FIREARM_TASERS         0
#define RESOURCE_SUBTYPE_FIREARM_HOLDOUTS       1
#define RESOURCE_SUBTYPE_FIREARM_LPISTOLS       2
#define RESOURCE_SUBTYPE_FIREARM_HPISTOLS       3
#define RESOURCE_SUBTYPE_FIREARM_MPISTOLS       4
#define RESOURCE_SUBTYPE_FIREARM_SMGS           5
#define RESOURCE_SUBTYPE_FIREARM_ASSAULTR       6
#define RESOURCE_SUBTYPE_FIREARM_SNIPERR        7
#define RESOURCE_SUBTYPE_FIREARM_SHOTGUNS       8
#define RESOURCE_SUBTYPE_FIREARM_SPECIALW       9
#define RESOURCE_SUBTYPE_FIREARM_MACHINEG       10
#define RESOURCE_SUBTYPE_FIREARM_LAUNCHERS      11
#define RESOURCE_SUBTYPE_AMMU_GRENADES          0
#define RESOURCE_SUBTYPE_AMMU_ROCKETS           1

// Weapon fire modi
enum WeaponFireModus
{
    WEAPON_FIRE_MODUS_INVALID = -1,
    WEAPON_FIRE_MODUS_SS,
    WEAPON_FIRE_MODUS_SA,
    WEAPON_FIRE_MODUS_BF,
    WEAPON_FIRE_MODUS_FA,
    NUM_WEAPON_FIRE_MODI
};
// Weapon clip types
enum WeaponClipType
{
    WEAPON_CLIP_TYPE_INVALID = -1,
    WEAPON_CLIP_TYPE_BREAK,
    WEAPON_CLIP_TYPE_CLIP,
    WEAPON_CLIP_TYPE_DRUM,
    WEAPON_CLIP_TYPE_MUZZLE,
    WEAPON_CLIP_TYPE_INT_MAG,
    WEAPON_CLIP_TYPE_CYLINDER,
    WEAPON_CLIP_TYPE_BELT,
    NUM_WEAPON_CLIP_TYPES
};

// Information about mounts
struct MountInfo
{
    QString id;
    QString location;
    bool    removable;
    char    rating;
};
